# Generated by Django 5.0.7 on 2024-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services"),
        ),
    ]
