# Generated by Django 5.0.7 on 2024-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="get_posts", to="blog.category"),
        ),
    ]
